### PR TITLE
Change copyright to GraphQL Contributors, License to MIT

### PR DESCRIPTION
**Pull request by acao**
@leebyron @caniszczyk  this should be it. Creating this PR in the official graphiql instead of the fork this time so it's part of the PR history

### CODE REVIEW

**Comment by acao** [comment]
@caniszczyk can we merge this today so we can merge the ide monorepo tomorrow?

**Comment by IvanGoncharov** [comment]
@acao In `graphql-js`, I just removed copyright headers see: https://github.com/graphql/graphql-js/pull/1960
Here is motivation for doing that: https://github.com/graphql/graphql-js/pull/1960#discussion_r291634984
I think would be great to do the same here to have consistency in all `graphql/*` projects.
What do you think?

**Comment by acao** [comment]
@IvanGoncharov I did this in a previous PR, but then @caniszyk asked me to re-introduce the headers with a different copyright message.

**Comment by IvanGoncharov** [comment]
>  I did this in a previous PR, but then @caniszczyk asked me to re-introduce the headers with a different copyright message.

@acao Totally makes sense in this case. Thanks for sharing context around this decision.

**Comment by acao** [comment]
@caniszczyk can you give this a review so we can merge for the WG meeting today?

**Comment by caniszczyk** [comment]
LGTM

**Comment by acao** [comment]
thank you!

**Pull request merged**
