### PR TITLE
Update babel configuration to target node for server packages

### PR DESCRIPTION
**Pull request by ganemone**
This updates the root babel configuration to target node for the server packages. This means the server packages can use native language features like async await, object spread, destructuring, etc.

This requires overriding configuration in the graphiql and codemirror-graphql packages to use the default configuration in @babel/preset-env.

### CODE REVIEW

**Comment by ganemone** [comment]
@acao - Thoughts on having separate targets for browser vs server packages? The main benefit of doing this is that it allows native language features which should be faster and is easier to debug if you end up debugging transpiled code.

I'm also not sure if I correctly captured the packages which are used in server vs browser. This has browser config only for `graphiql` and `codemirror-graphql`

**Comment by acao** [comment]
@ganemone good suggestion, however it's complicated because every package but the server is used in browsers as well. we have an upcoming PR that introduces a seperate babel config for graphiql. I will take a look at all of this later tonight

**Comment by acao** [comment]
youll see that the babel config for graphiql here #872 is a bit more nuanced. we can't just go with the preset-env defaults because we also need to decide when and where to inject regeneratorRuntime, and to have different targets for the library and CDN build. we might just end up introducing Rollup to solve this problem

**Comment by ganemone** [comment]
I will close this for now, since you are in the process of other build customization

**Comment by acao** [comment]
@ganemone thanks for opening it though, because it raises an important point, that we should be using `node: true` for server packages.

AFAIK, only `graphql-language-service-server` is the only package in this repo that runs *only* on a server. Everything else is designed to be isomorphic, even graphiql is built to be able to be rendered server side. Javascript is funny like that huh? 

It's just hard to decide how to distribute these packages for both server and browser runtimes. The `main` and `module` entrypoint pattern falls a bit short here IMO, as that has more to do with module systems than targets.

**Comment by acao** [comment]
@Neitsch re: `node: true`

**Pull request closed without merging**
