### PR TITLE
[redesign] add settings dialog

### PR DESCRIPTION
**Pull request by thomasheyenbrock**
Part of #2325

This adds the settings dialog. The only option for now is to clear the storage, theme selection will be added in the next PR.

### CODE REVIEW

**Comment by acao** [comment]
this is so exciting!

**Comment by acao** [comment]
this looks great so far, and the clear data toggle works, and is a fantastic start.


found this though, is this a known issue?
Screenshot 2022-07-27 at 19 27 55

**Comment by thomasheyenbrock** [comment]
Good catch! CodeMirror has some `z-index` set on the scrollbar containers which caused them to be above the dialog, should be fixed now.

**Review by acao — APPROVED** [review]
💯 ⚙️ 🤓 🚀

**Pull request merged**
