### PR TITLE
Added Codemirror 6 legacy mode support

### PR DESCRIPTION
**Pull request by imolorhe**
Implemented the codemirror.next legacy mode support for graphql mode.
This only covers syntax highlighting. Autocomplete, jump and info extensions
still need to be implemented to have feature parity with Codemirror v5.

From #2022

Before:
Screenshot 2021-11-21 at 4 52 55 PM

After:
Screenshot 2021-11-21 at 4 52 45 PM

### CODE REVIEW

**Comment by acao** [comment]
Thank you so much! Will review asap, working on monaco as we speak.

**Comment by acao** [comment]
@imolorhe also, if you add a changeset it will deploy a canary release :). Thanks for that @dotansimha !

**Review by acao — APPROVED** [review]
awesome work!  I think this is good to go.
let's go ahead and merge this, and then these steps will follow:

- a PR to change `codemirror-graphql` and `graphiql` to use `graphql-language-service` directly instead of interface, parser, and utilsl
- upgrade `graphiql` to use codemirror 6
- release!

**Comment by imolorhe** [comment]
I like the ambition but I'm afraid we shouldn't update graphiql to use cm5 just yet 😄

Codemirror 6 is officially still in beta so not sure it would be wise for us to use it just yet.

Also the changes introduced here only provide support for syntax highlighting. All the other nice things we have (autocompletion, jump, linting, etc) in codemirror 5 aren't supported yet.

Adding support for those would require that we create a new graphql parser class that is supported by codemirror 6, which would likely be a major lift.

**Comment by sergeichestakov** [comment]
FYI it looks like `@codemirror/*` packages should be specified as `peerDependencies` for published packages. I've opened a PR with more detail and a fix here: https://github.com/graphql/graphiql/pull/2369

pls let me know if that looks ok!

**Pull request merged**
