### PR TITLE
feat: add astro support for VSCode extension

### PR DESCRIPTION
**Pull request by XiNiHa**
Adds Astro syntax grammar support, language server parsing support, and misc wirings.

### CODE REVIEW

**Review by acao — APPROVED** [review]
awesome work! you even covered the esbuild script, very comprehensive, thank you!

**Comment by acao** [comment]
@XiNiHa just a few issues with dependencies, spelling and linting to clear up it looks like

**Comment by acao** [comment]
I'm about to merge a refactor for all of this that you will appreciate i'm sure, though it will cause a merge conflict

**Comment by acao** [comment]
@XiNiHa enjoy! let me know if you want me to redo it

**Comment by XiNiHa** [comment]
Sorry for being late to fix things up ;( I'll try to look at stuffs around this weekend

**Comment by acao** [comment]
@XiNiHa no worries, take your time!

also I improved the grammars a bit. let me know if you want to pair on this or have any questions.

**Comment by XiNiHa** [comment]
The language server doesn't work due to https://github.com/ardatan/graphql-tools/pull/5781 not being merged yet.

**Comment by acao** [comment]
@XiNiHa we have our own code parsing currently, but we added the graphql-config code parsing. There is a user working on astro for our parser as well in another PR

**Comment by acao** [comment]
two things!

1. can you add astro tests in findGraphQLParser-test.js 
2. I'm not sure why the graphql-language-service-server tests are failing for a missing astrojs-compiler-sync, even though it is added to package.json and seems to be reflected in yarn. can you try running yarn install again to update the lockfile?

**Comment by XiNiHa** [comment]
> I'm not sure why the graphql-language-service-server tests are failing for a missing astrojs-compiler-sync
Looks like a typo in the package.json of `astrojs-compiler-sync`, will make a PR on there

**Comment by acao** [comment]
awesome work!

sidenote: i think the issue with svelte2tsx is twofold - the language server needs to specify typescript as a dependency so that it works in non vscode contexts, and with vscode, we need to upgrade vsce as you have done and mark typescript as external. if we try to make it internal to the esbuild bundle it breaks as well. i can show you how to debug definitively - the vscode extension runner does not reflect the esbuild bundled state

**Comment by acao** [comment]
@XiNiHa this looks great! I will test the .vsix bundle manually just to be 100% certain. I think we can merge this and fix the svelte parsing in a single release

**Comment by acao** [comment]
I will take care of adding the tests in a follow up PR, but I might ping you later to make sure I've covered all the cases

**Pull request merged**
