### PR TITLE
[WIP]: chore: Update cypress e2e tests

### PR DESCRIPTION
**Pull request by harshithpabbati**
@acao just started with cypress testing :)

### CODE REVIEW

**Comment by acao** [comment]
fantastic, thank you!

in this PR you'll need to re-enable cypress for github actions:

https://github.com/graphql/graphiql/pull/1523/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R42

as you can see, the github action for Cypress shows as complete, however I disabled the suite, so it's showing success for everything but actually running cypress! haha

**Comment by acao** [comment]
ah, i will need to take this one over, as we still have issues with how webpack dist is being built

**Comment by harshithpabbati** [comment]
> ah, i will need to take this one over, as we still have issues with how webpack dist is being built

I was not able to get that working. It is showing 404 response on running the cypress tests.

**Comment by acao** [comment]
yes, thats because in the feature RFC branch, the dist has changed locations

**Comment by acao** [comment]
@harshithpabbati before creating new PRs, can you finish up this one?

**Comment by harshithpabbati** [comment]
> @harshithpabbati before creating new PRs, can you finish up this one?

Yea @acao, I made that PR because we need it over here to render the query, variables from the URI

**Pull request closed without merging**
