### PR TITLE
Add storybook+theme-ui for the new design

### PR DESCRIPTION
**Pull request by walaura**
This PR adds `storybook` and `theme-ui` to support the development of the redesign. there's some WIP components in `new-components` but they are more to test that storybook actually works than actual components at this stage so don't look at 'em too much.

this is how this looks like:

Screenshot 2019-12-21 at 10 39 57

### CODE REVIEW

**Comment by acao** [comment]
merged #1107 and a few dependabot PRs, but it looks like its just a minor yarn.lock conflict here!

**Comment by walaura** [comment]
we good on this end!

**Comment by acao** [comment]
@walaura so do you want to add this to the netlify build? you’ll just want to add build-storybook to a new “build-demo” script in “packages/graphiql” that builds to somewhere like packages/graphiql/storybook (will need to be gitignored). Then netlify will build it as the last step. Then yoll be able to see it in the deploy preview on each commit

**Comment by acao** [comment]
eyyyyy
https://deploy-preview-1145--graphiql-test.netlify.com/storybook/

looking nice!

**Comment by walaura** [comment]
yasss!!! whats shall we do about codecov? I can do snapshots for the components as they are now but I really don't think they'll last more than 2 PRs

**Comment by acao** [comment]
good question! i think we can exclude stories and the theme from  coverage. as for components, snapshots make sense. codecov is annoying sometimes haha

**Comment by walaura** [comment]
@acao anything i should do on my end to make that happen?

**Comment by acao** [comment]
as for excluding coverage, you can just add more lines with exclamation points to the jest.config.js
for snapshots, there seems to be a few guides to using storybook 2 with jest snapshot testing, but also some RTL tests sound good if that makes sense? there is so little to test yet, haha

**Comment by walaura** [comment]
really can't imagine a use for real tests right now so what i can do is we either ignore this or I can delete some of the scrap components?

**Comment by acao** [comment]
lets just ignore all of new components and everything storybook related  in the jest config. i agree this is where blocking on coverage seems unnecessary. also if its ready i can merge  it anyways after  doing a quick review?

**Comment by walaura** [comment]
yes! go for it ^^ i added snaps and blocked the theme and stories from coverage so this lasy built might actually go green. if it doesn't feel free to ignore the whole folder for now?

**Comment by acao** [comment]
ah, so close! can you just tweak that one jest config line to ignore the whole `new-components` for now? if not I can still force merge and create another PR to ignore the folder since I can't commit to this one

**Comment by acao** [comment]
oh also some kinda funky bug:
Screen Shot 2019-12-22 at 11 49 40 AM
strange because there is definitely a `theme.colors.border`... hmm!

**Comment by walaura** [comment]
ooooh, gotta add the context inside the testing scaffold i guess! lemme figure this out on monday. also find out where's the 'allow contributors to push' checkbox

**Comment by walaura** [comment]
oh yeah you should be good to edit?
Screenshot 2019-12-22 at 17 42 48

**Comment by acao** [comment]
oh awesome! thank you! i didnt know about that, handy! would you like me to
take care of that today? jest ignore and context? monday is fine too,
whatever’s clever

**Comment by walaura** [comment]
> oh awesome! thank you! i didnt know about that, handy! would you like me to take care of that today? jest ignore and context? monday is fine too, whatever’s clever
> […](#)

kinda wanna look at context in tests myself! never done it before and i'm curious to see how jest handles this idiomatically. So I guess yeah let's do it on Monday!

**Comment by acao** [comment]
awesome, yeah have at it! there’s no huge rush. will be awesome if we can
set some patterns for that, as we will have a few more contexts on the way
soon! ill be around, let me know how it goes, I’ll be available here or on
discord!  thanks for helping! hope youve had a lovely weekend!

**Pull request merged**
