### PR TITLE
Fix: explorer title is not selectable anymore #778

### PR DESCRIPTION
**Pull request by kayhadrin**
Fix issue that was introduced in 0e85c75 (#232)

### CODE REVIEW

**Comment by kayhadrin** [comment]
Ping ping ping! :-)

**Comment by kayhadrin** [comment]
@captbaritone EZ fix :-)

**Comment by daern91** [comment]
Thanks a lot, @kayhadrin! We are also facing this problem and can confirm that this PR solves it.

ping @AGS- and @asiandrummer

**Comment by orta** [comment]
Alright, let's get this in - feels like a safe PR. :+1:

**Pull request merged**
