### PR TITLE
feat: add all schema types in schema documentation

### LINKED ISSUE #3000: [graphiql] Display more types in `<SchemaDocumentation />`
Hello 👋 

Currently, SchemaDocumentation shows only the root types in the initial screen, and has a lot of screen real estate that could be used to show more types. That would bring the UI closer to the results of `{ __schema { types { name } } }` query, so it's IMHO both a nice use of the empty space an pretty consistent.

I'm up for sending a PR if you feel it would be a worthwhile contribution. With `TypeLink` and `schema.getTypeMap()` the implementation seems be pretty straightforward.

<details>

<summary>Got a hacky implementation working with `pnpm patch`.</summary>

```diff
@@ -19643,6 +19634,9 @@ function SchemaDocumentation(props2) {
   const queryType = props2.schema.getQueryType();
   const mutationType = (_b = (_a = props2.schema).getMutationType) == null ? void 0 : _b.call(_a);
   const subscriptionType = (_d = (_c = props2.schema).getSubscriptionType) == null ? void 0 : _d.call(_c);
+  
+  const typeMap = props2.schema.getTypeMap && props2.schema.getTypeMap();
+  
   return /* @__PURE__ */ jsxs(Fragment, {
     children: [/* @__PURE__ */ jsx(MarkdownContent, {
       type: "description",
@@ -19671,6 +19665,29 @@ function SchemaDocumentation(props2) {
           type: subscriptionType
         })]
       })]
+    }), !typeMap ? null : jsxs(ExplorerSection, {
+      title: "Possible Types",
+      children: [
+        Object.values(typeMap).map(typeValue => {
+          const renderedKinds = [
+            "Interface",
+            "Object",
+          ].map(s => `GraphQL${s}Type`)
+
+          const ctorName = typeValue.constructor.name
+          const typeName = typeValue.name;
+
+          const ignoredTypes = ['Query', 'Subscription'];
+
+          if (renderedKinds.includes(ctorName) && !ignoredTypes.includes(typeName) && typeName[0] !== '_') {
+            return jsxs("div", {
+              children: [jsx(TypeLink, { type: typeValue })],
+            })
+          }
+
+          return null;
+        })   
+      ]
     })]
   });
 }
@@ -19811,7 +19828,6 @@ function fillInChunks(_ref4) {
       });
     }
   }
 }
 ```

</details>

https://user-images.githubusercontent.com/15332326/213796151-c92d1c8b-3bb4-49ef-8630-a6ace29ddb83.mov

As alternatives, I've considered disabling the Documentation Explorer plugin and swapping it with my own version, and mutating `DOC_EXPLORER_PLUGIN` export like a bandit, but I feel like it would be nice to have this feature in all GraphiQLs, not only in mine :)

### PR DESCRIPTION
**Pull request by Zolwiastyl**
closes #3000

Adds new explorer section "all schema types".

Todo:
- [ ] disable/enable via plugin setting

Is any margin needed for those listed types?
Do we want to keep those types beginning with `__`?

Screenshot 2023-03-04 at 13 45 31

### CODE REVIEW

**Comment by hasparus** [comment]
> Do we want to keep those types beginning with __?

I think I'd filter them out. They don't communicate any knowledge about the GraphQL API's domain.

**Comment by acao** [comment]
@Zolwiastyl awesome work! can you add a changeset

And yes, you can filter out the introspection types (the types that start with `__`). 

I can think of some advanced use cases where someone developing a graphql server would need to review them, especially when adapting new spec versions this would be useful, but if someone needs that they can ask for it.

**Comment by Zolwiastyl** [comment]
@acao thanks, added changeset and filtering out introspection types

**Comment by acao** [comment]
@Zolwiastyl i think this is ready! if you want to see a working deploy preview, you can just push a new commit or force push a commit

**Comment by hasparus** [comment]
I'm glad that this PR is alive <3
image

**Comment by Zolwiastyl** [comment]
@acao  Hi, I've merged main into my branch - it looks good and all green now 😄

**Comment by acao** [comment]
@Zolwiastyl if you wanted to make this configurable, you would just add it to the props, but I think we can go with this for now, and if people request it we can make it configurable.

**Pull request merged**
