### PR TITLE
Fix warnings for invalid className attributes

### LINKED ISSUE #723: Warning: Received `false` for a non-boolean attribute `className`
Keep getting the following warning in the console log when using GraphiQL:
```
index.js:170 Warning: Received `false` for a non-boolean attribute `className`.

If you want to write it to the DOM, pass a string instead: className="false" or className={value.toString()}.

If you used to conditionally omit it with className={condition && value}, pass className={condition ? value : undefined} instead.
    in p (created by HistoryQuery)
    in HistoryQuery (created by QueryHistory)
    in div (created by QueryHistory)
    in div (created by QueryHistory)
    in QueryHistory (created by GraphiQL)
    in div (created by GraphiQL)
    in div (created by GraphiQL)
    in GraphiQL
warningWithoutStack @ index.js:170
```
This is my application entry point:
```
import '@babel/polyfill';
import 'raf/polyfill';

import React from 'react';
import ReactDOM from 'react-dom';
import GraphiQL from 'graphiql';
import axios from 'axios';
import 'graphiql/graphiql.css';
import '../Content/graphiql.css';

function graphQLFetcher(graphQLParams) {
  return axios({
    method: 'POST',
    url: './api/graphql',
    data: graphQLParams
  }).then(resp => resp.data);
}

ReactDOM.render(<GraphiQL fetcher={graphQLFetcher} />, document.getElementById('app'));
```
The page renders ok and GraphiQL seems to work as normal but the warning is always there. The page itself contains nothing except the 'app' div hosting React and GraphiQL.

### PR DESCRIPTION
**Pull request by tomraithel**
Fixes #723

### CODE REVIEW

**Comment by motleydev** [comment]
Any idea when this might get merged in?

**Comment by askesis** [comment]
really, why is it still not merging ? I just hate this warning lately

**Comment by AGS-** [comment]
Sorry about taking so long! @tomraithel thanks for fixing this!

**Comment by DanielMSchmidt** [comment]
Could it be that there was no release so far with that fix included?

**Comment by heatherbooker** [comment]
I just updated to `0.13.2` and the error is gone 🙌

**Pull request merged**
