### PR TITLE
Update typo in editor startup message

### PR DESCRIPTION
**Pull request by leereilly**
Noticed a small typo in the welcome message. I think `starts` (plural) should be `start` (singular)...

Screen_Shot_2021-02-09_at_5_20_39_PM

Cheers,
&nbsp;&nbsp;Lee

### CODE REVIEW

**Comment by acao** [comment]
@leereilly this is an amazing catch, thank you, I somehow never noticed this!

can you backport the correction to `packages/graphiql/src/GraphiQL.tsx` as well?

**Comment by leereilly** [comment]
Ha ha - you're welcome 😆 

It looks like it's already correct in..here? https://github.com/graphql/graphiql/blob/237c7abc8307729c948d22a3fae48634c875334c/packages/graphiql/src/components/GraphiQL.tsx#L1696

(I didn't attempt to build it... I just searched for troublesome string)

**Comment by acao** [comment]
hmm ok! the 1.x branch has upstream improvements confusingly enough. the 2.0.x rfc you added to in this PR was a conversion to modern react/context from last year, there are new plans afoot

the version you are using must be GraphiQL.app or something that bundles our build in a desktop app? so they must have bundled an older version then

**Comment by leereilly** [comment]
Oh gotcha - I _may_ have been guilty of just doing ` brew install graphiql --cask` and making some assumptions. 

That gave me `Version 0.7.2 (0.7.2)`. 

I'm going to assume it's more than a version bump to https://github.com/skevy/graphiql-app/blob/36f4695ad10e6406d81f15f3f44a9a61d7be8e48/package.json#L33, but if you think it's worth a try, I'll give a shot!

**Pull request closed without merging**
