### PR TITLE
use latest typescript version in lsp server

### PR DESCRIPTION
**Pull request by acao**
make sure to use the latest version of typescript. i get confused with the autocomplete and copilot, oops!

### CODE REVIEW

**Comment by samchungy** [comment]
Hey @acao my vscode has been crashing non stop since the latest 2 PRs.

0.8.22 seems to be fine

```
Error: Cannot find module 'typescript'
Require stack:
- /Users/samc/.vscode/extensions/graphql.vscode-graphql-0.8.24/out/server/index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1129:15)
    at Module._load (node:internal/modules/cjs/loader:974:27)
    at f._load (node:electron/js2c/asar_bundle:2:13377)
    at Module.require (node:internal/modules/cjs/loader:1195:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at /Users/samc/.vscode/extensions/graphql.vscode-graphql-0.8.24/out/server/index.js:4355:5291
    at /Users/samc/.vscode/extensions/graphql.vscode-graphql-0.8.24/out/server/index.js:1:264
    at /Users/samc/.vscode/extensions/graphql.vscode-graphql-0.8.24/out/server/index.js:4441:2810
    at /Users/samc/.vscode/extensions/graphql.vscode-graphql-0.8.24/out/server/index.js:1:264
    at /Users/samc/.vscode/extensions/graphql.vscode-graphql-0.8.24/out/server/index.js:4441:4643 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/samc/.vscode/extensions/graphql.vscode-graphql-0.8.24/out/server/index.js'
  ]
}
```

**Comment by samchungy** [comment]
https://github.com/graphql/graphiql/blob/f5ade688043409bd9ad80f07737ce43442d56ee6/packages/vscode-graphql/esbuild.js#L52

Ah it looks like this might be the cause? ^

**Comment by acao** [comment]
perhaps, let's try without that. I can't re-create the issue locally, because the runner doesn't expose this issue. i will upload an VSIX here

**Comment by acao** [comment]
@samchungy can you try this version to verify that disabling the external rule works?

https://drive.google.com/file/d/15v-tdLbu_z69O0qWpysfQfMI69Hk1SpO/view?usp=sharing

**Comment by acao** [comment]
no, that does not work either. we have to revert this svelte PR it looks like

**Comment by acao** [comment]
@samchungy 0.8.25 should be the fix version, it will be released in a few minutes. I manually tested it. It degrades svelte parsing significantly until we figure out a better solution.

**Comment by samchungy** [comment]
Much appreciated 🙇. It's pretty late where I am so I'll give it a spin tomorrow :)

**Comment by samchungy** [comment]
@acao 0.8.25 seems to work fine! Thanks for the speedy fix once again! 😄

**Pull request merged**
