### PR TITLE
update cypress to v12.6.0

### PR DESCRIPTION
**Pull request by B2o5T**
fixes https://github.com/graphql/graphiql/issues/2879

### CODE REVIEW

**Comment by acao** [comment]
image

interesting, the only failure is just an error changing, i think for essentially the same error though?

**Comment by B2o5T** [comment]
@acao yeah, seems like it is the same error but printed differently, will take a look later 🙂

**Comment by acao** [comment]
@B2o5T looks like requests are failing, is there a change that needs to be made to specify the url differently now?

**Comment by B2o5T** [comment]
I will retry this week!

**Review by jonathanawesome — APPROVED** [review]

**Review by acao — APPROVED** [review]
great work, thanks @B2o5T !

**Pull request merged**
