### PR TITLE
yarn => pnpm

### PR DESCRIPTION
**Pull request by rxliuli**
ref: https://github.com/graphql/graphiql/issues/2185

### CODE REVIEW

**Comment by acao** [comment]
@rxliuli ah, the email used for CLA has to be the same email that’s used in each commit

**Comment by acao** [comment]
It looks like we need to use a base image that already has pnpm ideally, or we can manually install pnpm for each workflow

**Comment by rxliuli** [comment]
> It looks like we need to use a base image that already has pnpm ideally, or we can use an action to manually install pnpm for each workflow

Just run `npm i -g pnpm`

**Comment by acao** [comment]
@rxliuli don‘t tell me, tell the github actions 😂

**Review by acao — CHANGES_REQUESTED** [review]
please update the github actions to install pnpm, preferrably in the base docker image, so that CI passes. As you can see, all 18 checks are failing

**Comment by rxliuli** [comment]
Do you want to change the command to install dependencies on netlify? I have observed that the dependencies are still installed using npm and then fail

https://app.netlify.com/sites/graphiql-test/deploys/625f4fd9e4fab7000994463a

**Comment by acao** [comment]
@rxliuli weird, not sure why i had to re-approve them!

**Comment by rxliuli** [comment]
Build & Test I know what's wrong, it's fixed. But why does lint fail, it seems strange, do I need to fix these lint and ts errors? Or some configuration was accidentally changed. . .

https://github.com/graphql/graphiql/runs/6087316492?check_suite_focus=true

**Comment by acao** [comment]
@rxliuli something is off with lint staged, so for now you need to run pnpm format.

**Comment by acao** [comment]
Hmm, the typescript version must be resolving differently, either way you can use the ts-expect-error comment if you want since they are mostly just handling errors

**Comment by rxliuli** [comment]
I restored the version of the dependencies from the previous yarn.lock, including typescript, sorry, I didn't notice the change of the dependency version before

**Comment by rxliuli** [comment]
webpack4 is not compatible with pnpm, it's a bit tricky, have you guys done webpack4 => webpack5? Or we can use rollup?
https://github.com/webpack/webpack/issues/5087

**Comment by timsuchanek** [comment]
I think @acao was thinking of Vite, which I'd be totally ok with.
From my side you can go ahead and move to Vite.
Curious what @acao thinks

**Comment by acao** [comment]
Our plan was to migrate to vite instead, and drop babel and webpack altogether. But we may have to upgrade to webpack 5 as a transitional step. It will have to wait as I’m sick with covid and my co maintainers are focused on other things at the moment

**Comment by acao** [comment]
With vite the goal was to get rid of the duplicate typescript project references tree and use vite to bundle each library for it‘s relevant exports, but I’m having trouble finding something that can re-create tsc —build —watch on a monorepo scale. @nx might have something for this, I can’t seem to find any vite and/or rollup plugins that solve this problem

**Comment by rxliuli** [comment]
> This was the blocker we had run into before with pnpm, thus why i raised the issue of webpack support early on! Our plan was to migrate to vite instead, and drop babel and webpack altogether. But we may have to upgrade to webpack 5 as a transitional step. It will have to wait as I’m sick with covid and my co maintainers are focused on other things at the moment

Is there any suggestion, currently only one **Test PR / Cypress E2E Suite (pull_request) ** can not pass, I don't use webpack very much so don't know much about the configuration here
packages/graphiql/resources/webpack.config.js

**Comment by rxliuli** [comment]
> With vite the goal was to get rid of the duplicate typescript project references tree and use vite to bundle each library for it‘s relevant exports, but I’m having trouble finding something that can re-create tsc —build —watch on a monorepo scale. `@nx` might have something for this, I can’t seem to find any vite and/or rollup plugins that solve this problem

In production, we wrote a plugin to handle this, pointing the module to src/index.ts so that we don't have to rebuild dist/index.js every time the lib is modified

ref: https://github.com/rxliuli/liuli-tools/blob/master/libs/rollup-plugin-ts-alias/README.md

**Comment by acao** [comment]
Like I mentioned in #2185, you will need to find a compatibility mode or workaround for webpack 4, jest, cypress, etc, which has been what kept us from switching to pnpm im previous attempts.


Otherwise a webpack 5 upgrade will take some sizeable effort and will definitely need to come in a separate PR, since it heavily impacts the actual bundle we ship to the CDNs, which is used more than even the esm module!

**Comment by acao** [comment]
@rxliuli that plugin looks very promising thanks! Apologies there seems to be a delay with my LTE connection, each of your comments is only visible once I make a comment? So I’m just seeing your reply now

**Comment by acao** [comment]
I think we can do this best in two or more PRs:

1. swap out webpack for vite - we don’t need to worry about bundling every library yet. Leave duplicate project references for now. Merge.
2. then, rebase this PR for pnpm with that upstream change
3. Then, worry about replacing the duplicate references for a modern bundling and even `exports` strategy in an additional PR

**Comment by timsuchanek** [comment]
Thanks for providing this context @acao ! That plan makes total sense to me.
@rxliuli do you have capacity to work on the steps Rikki outlined?

**Comment by rxliuli** [comment]
> Thanks for providing this context @acao ! That plan makes total sense to me. @rxliuli do you have capacity to work on the steps Rikki outlined?

I will try it tomorrow

**Comment by acao** [comment]
closing for #3054

**Pull request closed without merging**
