### PR TITLE
Add graphql 14.0.0 to peer dependencies

### PR DESCRIPTION
**Pull request by jxltom**
Closes https://github.com/graphql/graphiql/issues/739

### CODE REVIEW

**Comment by unindented** [comment]
@jxltom I believe it should be `^14.0.0`, as `0.14.0` doesn't exist.

**Comment by jxltom** [comment]
@unindented Oh, Thanks!

**Comment by unindented** [comment]
@AGS- any chance of seeing this merged and published before the end of the year?

**Comment by williaster** [comment]
also would love this

**Comment by ggascoigne** [comment]
Any chance of a release containing this change?

**Comment by mohsen1** [comment]
@AGS- Can you please take a look at this? Using GraphiQL with other GraphQL dependencies is resulting in lots of peer dependency issues and warnings. I would appreciate merging and releasing this! Thank you!

**Comment by AGS-** [comment]
Oh sorry, didn't realize there was a PR for this. Updated it and cut a release. Thanks for taking the time to contribute!

**Pull request closed without merging**
