### PR TITLE
Use the prod distribution of React instead of dev in the CDN example

### PR DESCRIPTION
**Pull request by kiendang**

### CODE REVIEW

**Comment by acao** [comment]
we are already doing this in #3380

**Comment by acao** [comment]
thanks, though!

**Comment by kiendang** [comment]
Maybe I don't understand it fully, but that PR is for the `graphiql-webpack` example not the `graphiql-cdn` example no?

The reason for this PR is there are GraphQL frameworks out there like [strawberry](https://github.com/strawberry-graphql/strawberry) and [graphene-django](https://github.com/strawberry-graphql/strawberry) that serve GraphiQL and use the CDN example here as reference. Because of this sometimes they just copy paste and ended up shipping with react development which is 10 times the size of `production.min.js`. [Example](https://github.com/strawberry-graphql/strawberry/blob/4eb629ebc99f1ddfa82fa7ff0f2f369f1d3b5112/strawberry/static/graphiql.html#L46).

 Maybe it's worth changing here too?

**Comment by tyranron** [comment]
@acao ping... I do agree with @kiendang here. Would you mind to reconsider this PR?

**Comment by acao** [comment]
does https://graphiql-dev.netlify.app/webpack not work? what is the purpose in particular?

**Comment by tyranron** [comment]
@acao it seems to me that @kiendang stated the problem quite clear:

> The reason for this PR is there are GraphQL frameworks out there like [strawberry](https://github.com/strawberry-graphql/strawberry) and [graphene-django](https://github.com/strawberry-graphql/strawberry) that serve GraphiQL and use the CDN example here as reference.

The choice of the `graphiql-cdn` example is obvious, because they do not want to bother with webpack and/or other toolchains just to serve the GraphiQL page. So, they mostly use it "as is", adjusting it [only in few bits to work with the framework](https://github.com/strawberry-graphql/strawberry/blob/4eb629ebc99f1ddfa82fa7ff0f2f369f1d3b5112/strawberry/static/graphiql.html#L134), but do not re-check optimality of the dependencies. And then things go viral, because every framework has its users.

> Because of this sometimes they just copy paste and ended up shipping with react development which is 10 times the size of `production.min.js`.

**Comment by acao** [comment]
oh this is for the cdn example! that makes sense

**Comment by acao** [comment]
really, we should be showing how to use `<script type="module">` as modern browsers don't need UMD anymore but that's another matter

**Comment by kiendang** [comment]
Thanks a lot @tyranron for the clarification 👍 

@acao let me know if there's anything else needed to get this merged.

**Review by dimaMachina — APPROVED** [review]
I updated other examples too

**Pull request merged**
