### PR TITLE
Clicking on documentation title takes you back to the root

### PR DESCRIPTION
**Pull request by wincent**
As suggested on #139 by @asiandrummer.

Closes: https://github.com/graphql/graphiql/issues/139

### CODE REVIEW

**Comment by wincent** [comment]
Note that this solution isn't the most discoverable thing in the world, but its presence isn't actively harmful either. We might still want to add something visible (like a home icon, or breadcrumbs) in a separate PR.

**Comment by leebyron** [comment]
Dunno about this, it's pretty unintuitive to click the name of the type you're currently looking at documentation for and clear your nav stack. If someone does this unintentionally they'd probably be upset about it.

Let's come up with a nicer design for this functionality

**Comment by leebyron** [comment]
Also - I'd push against the need for this in the first place - the way you end up with a deep nav stack is by navigating deeply in the first place, so heading back is more important.

What's the drive to get back to "home", is it to get back to the search bar? Maybe we should just make the search bar more omni-present

**Comment by asiandrummer** [comment]
I agree with more omni-present search bar, but I do see some value with going back to the doc's main page, maybe with a button. It's an easy way to look at the root types/fields if you aren't necessarily sure which types are the root types.

**Comment by leebyron** [comment]
I'm not saying there's no value in it, but we need to weigh that against the pixel real-estate a button would consume or the interaction complexity cost of sticking it somewhere undiscoverable or surprising.

You can get back to "home" now by repeatedly clicking the back arrow, which sure is more clicks than one if you nav'd deeply, but I'm not sure that getting back to learn if you named your query root type "Query" or "QueryRoot" is worth reducing a few clicks into one click and a persistent button

**Comment by wincent** [comment]
> I'm not saying there's no value in it, but we need to weigh that against the pixel real-estate a button would consume

Given media queries, I don't think we need to worry too much about that, although I agree it's not *super*-valuable to have this (I was just picking off some issues to become familiar with the codebase).

Here's what I would probably want in a design at a few different breakpoints:




Wide screen:

```
--\----------\----------------------------------------------------------------
   \          \
/\  \   Type   \                     Child Type                            X
||  /          /
   /          /
--/----------/----------------------------------------------------------------
```


Medium screen:

```
-------\------------------------------------------------
        \
  Type   \              Child Type                   X
         /
        /
-------/------------------------------------------------
```

Tiny screen:

```
--------------------------------------------

  /          Child Type                   X
  \

--------------------------------------------
```

Hashtag: #NotADesigner

**Comment by leebyron** [comment]
That's an interesting idea, but maybe less helpful if it's only available when you expand the explorer extra wide - I think something like that would be really useful for a full-screen doc explorer as something that's persistently available regardless of where you are in the docs that's like a link back to index.

For the smaller screen space of the in-tool doc explorer I'd be worried about [Fitt's Law](https://www.interaction-design.org/literature/article/fitts-s-law-the-importance-of-size-and-distance-in-ui-design) with the back button and home button necessarily close to each other.

I like the idea of dropping the previous type's name from the back button when the explorer is small though! Right now it truncates it with an ellipsis, but that gets pretty messy looking.

**Comment by leebyron** [comment]
Also @wincent that's some pro ASCII art

**Comment by wincent** [comment]
> I like the idea of dropping the previous type's name from the back button when the explorer is small though! Right now it truncates it with an ellipsis, but that gets pretty messy looking.

Ok, I'll upload something that does that:

graphiql

graphiql_and_yarn___glh-mbp___masochist___graphiql__tmux_

**Pull request closed without merging**
