### PR TITLE
feat: add syntax highlighting in Scala

### PR DESCRIPTION
**Pull request by hugo-vrijswijk**
Adds syntax highlighting for graphql\gql strings in Scala
image

### CODE REVIEW

**Comment by acao** [comment]
awesome work @hugo-vrijswijk ! are there any other lesser known approaches to deliminating graphql strings used in scala? or does this cover most of them? I'm only aware of Sangria which seems to avoid using literal graphql document strings even for client queries, But I also have no idea where to look, haha.

**Comment by hugo-vrijswijk** [comment]
I realized I forgot 1 actually: `schema"""`, which is how [Grackle](https://github.com/gemini-hlsw/gsp-graphql) defines schemas. Sangria does support graphql strings, but I also added this with an eye to [Clue](https://github.com/gemini-hlsw/clue) for client queries

**Comment by acao** [comment]
@hugo-vrijswijk awesome! one last thing - if you can add to the README for us, the various deliniation rules for Scala? This helps with setting some expectations and at least code examples to test until we add automated tests for syntax highlighting

**Comment by hugo-vrijswijk** [comment]
> @hugo-vrijswijk awesome! one last thing - if you can add to the README for us, the various deliniation rules for Scala? This helps with setting some expectations and at least code examples to test until we add automated tests for syntax highlighting

Good point, I've added it to the readme

**Comment by hugo-vrijswijk** [comment]
@acao bump 👀🙏

**Review by acao — APPROVED** [review]
hey @hugo-vrijswijk ! thanks for addressing the final docs nit. this is ready to release now, looking forward to it!

**Pull request merged**
