### PR TITLE
Link the GraphiQL logo to this repository

### PR DESCRIPTION
**Pull request by mxstbr**
…so that more developers will find the repository and potentially turn into contributors!

### CODE REVIEW

**Comment by acao** [comment]
@mxstbr this is a great idea!!!

(P.S. the CLA bot just wants you to use the same email for the commit that you've signed the CLA with)

**Review by thomasheyenbrock — CHANGES_REQUESTED** [review]
We should add some style overrides for this, otherwise the default styles kick in which will make the font purple
CleanShot 2022-08-26 at 17 54 21@2x

**Comment by mxstbr** [comment]
As far as I can tell, I've already signed the CLA: https://github.com/graphql/EasyCLA/pull/21

**Comment by mxstbr** [comment]
Fixed the styling! 🙌

**Comment by mxstbr** [comment]
CleanShot 2022-08-27 at 14 34 26@2x

Fixed the styling!

**Comment by acao** [comment]
@mxstbr oh ok, it was showing a failing check yesterday for some reason. All looks good now!

**Review by thomasheyenbrock — APPROVED** [review]

**Comment by thomasheyenbrock** [comment]
Awesome, thanks @mxstbr 🙏

**Pull request merged**
