### PR TITLE
chore: add no-only-tests to eslint

### PR DESCRIPTION
**Pull request by ryan-m-walker**

### CODE REVIEW

**Comment by acao** [comment]
@ryan-m-walker i think the easier way would be to use the jest plugin `no-focused-tests` rule:
https://github.com/jest-community/eslint-plugin-jest/blob/master/docs/rules/no-focused-tests.md

**Comment by acao** [comment]
oh hey! https://github.com/graphql/graphiql/pull/1174

**Comment by ryan-m-walker** [comment]
@acao switched over to jest

**Comment by acao** [comment]
i did this already. i enabled jest-reccomended

**Comment by ryan-m-walker** [comment]
@acao haha awesome i'll close this

**Comment by acao** [comment]
sorry forgot to reference this PR. I'm adding a few more tweaks to this PR too, just some handy improvements

**Comment by acao** [comment]
thanks for the initiative though! i'll give you credit in the squash commit.

**Comment by ryan-m-walker** [comment]
no problem

**Pull request closed without merging**
