### PR TITLE
Add test scaffolding for vscode-graphql-syntax

### PR DESCRIPTION
**Pull request by AaronMoat**
Resolves: #2343

Saw the discussion in #3217 and wanted to revive the older discussion in #2343. Main question - do we think this approach will be helpful, or should we look into something more style/visual based?

### CODE REVIEW

**Comment by AaronMoat** [comment]
Ok, immediate problem, prettier autoformatting indents comments, whereas the package doesn't support unit tests unless the line literally starts with #

**Comment by acao** [comment]
@AaronMoat this is awesome! I find it visual enough for our needs. and also, prettier should not be formatting snapshots anyways!

**Comment by AaronMoat** [comment]
Hi @acao, I was actually talking about the `unit` tests. You can do stuff like... 

```graphql
query {
  something
# ^ do some assertions here
}
```

But prettier adds two spaces before the `#` and the "unit test" assertion no longer runs. I suppose we could ignore just the plain .graphql files too 🤔 

I'm tempted to see what this stuff looks by-hand with jest, etc, anyway, I'll have a play and put an alternate PR up (if I get something sensible)

**Comment by acao** [comment]
we shouldn't ignore all plain .graphql files, but if you need them for this, you can set specific ignore rules for these unit tests. this is the only syntax extension so it would make sense.

sure, jest sounds nice! @B2o5T wants to move to vitest. I just made it so that jest doesn't need a `build` step anymore, except for `cm6-graphql`, so you can run `yarn test` without and build steps being necessary, enjoy!

**Comment by AaronMoat** [comment]
Have put an alternative in https://github.com/graphql/graphiql/pull/3273 😄

**Comment by AaronMoat** [comment]
Closing in favour of https://github.com/graphql/graphiql/pull/3273

**Pull request closed without merging**
