### PR TITLE
Replace React.PropTypes with prop-types package

### PR DESCRIPTION
**Pull request by Hypnosphi**

### CODE REVIEW

**Comment by asiandrummer** [comment]
@Hypnosphi seems like we have a conflict :)

**Comment by Hypnosphi** [comment]
> Seems like https://facebook.github.io/react/docs/typechecking-with-proptypes.html encourages this - thanks for the contribution!

As well as React's warnings do since 15.5 =)

**Comment by Hypnosphi** [comment]
I've removed `yarn.lock` from commit's tree to prevent further conflicts

**Comment by Hypnosphi** [comment]
One more release maybe?

**Comment by AGS-** [comment]
@Hypnosphi I may cut another release today

**Pull request merged**
