### PR TITLE
Symbol support for single document

### PR DESCRIPTION
**Pull request by acao**
Originally based on
https://github.com/graphql/graphql-language-service/pull/195

Works a charm with https://github.com/prisma-labs/vscode-graphql

**HTD**:
1. clone vscode-graphql, npm install
2. from graphiql/packages/graphql-language-service-server, `yarn link`
3. yarn build graphiql
4. open `vscode-graphql` in vscode, `yarn link graphql-language-service-server` and launch 'Extension' in debugger panel
5. An instance of vscode will open. open a directory containing a .graphqlconfig with a url (see server tests for an example file) and a .graphql file in the same directory. You'll see schema-driven completion, diagnostics, etc
6. Finally, test the new capabilities: ensure that you can peek object/input object/fragment/query argument definitions of any type, and that you can see an outline in vscode of at least the fragment and operation definitions.

Screen Shot 2020-01-26 at 7 11 52 PM

**TODO**:
- [x] handle document-wide symbol requests for operations
- [x] add outline support for SDL/IDL/schema definition types
- [x] handle document-wide symbol requests for schema types (thanks to above) (symbols are where the outline items get their icons for example. much more to come there!)
- [x] show outlines in vscode!
- [ ] more tests for GLS interface symbol/outline support
- [ ] workspace-wide symbols (in another PR possibly?)
- [ ]  handle references request  (in another PR possibly?)

### CODE REVIEW

**Comment by acao** [comment]
seems there was an issue where the last amended push on publish didn't end up in master

**Comment by acao** [comment]
@divyenduz do you wanna give this a spin and let me know if im missing anything?

**Comment by acao** [comment]
I think we can do this in a seperate PR:
https://github.com/graphql/graphiql/pull/1244/files#diff-0094c9d6723c3042b174037952ce1078R191

**Comment by divyenduz** [comment]
I gave it a spin, looks good to me. I might not know it completely but fields (`success`) and arguments (`title`, `content`) look alike, is that expected? 

CleanShot 2020-02-05 at 00 17 32@2x

**Comment by acao** [comment]
ah yes, these icons are reflections of the symbol types!

the purpose here is that the purple icon is a field with arguments, as it acts kinda like a function. in this case, title and content are arguments for the field `createPost` right? i wasnt sure how else to represent a field with arguments other than with a SymbolKind.Method and SymbolKind.Parameter

**Pull request merged**
