### PR TITLE
feat(subscriptions): added graphql-subscriptions support

### PR DESCRIPTION
**Pull request by Urigo**
Adding subscriptions support with the [subscriptions-transport-ws](https://github.com/apollographql/subscriptions-transport-ws) library.

Replaced dummy subscription with timeSubscription and publish it every second.

### CODE REVIEW

**Comment by asiandrummer** [comment]
Hi @Urigo - I'm not sure if `graphiql` repo is the right place for this. What is the intention of this addition?

**Comment by leebyron** [comment]
I agree with @asiandrummer - If `subscriptions-transport-ws` wishes to include test coverage that it works with GraphiQL, then you should add this sort of test to that repo, but I don't think it's appropriate for GraphiQL's test cases to be subscription-specific when the large majority of usage is not subscriptions and subscriptions are still in the early phase of RFC where changes are possible. 

I'd prefer that we don't introduce volatility into GraphiQL's test harness until subscriptions are supported in a more first-class way, and that when we do so we don't upset the existing test coverage.

**Comment by Urigo** [comment]
@asiandrummer @leebyron sorry got the late response.
I totally agree that while we are in RFC process this should not be merged.
Also, I agree about making the transport not subscriptions specific and we are working on that (updates soon).

Maybe we could leave this PR open as kind of RFC like thing for GraphiQL and subscriptions?
While working on that a lot of questions came up, also in simple terms of the right UI for subscriptions (When new results come - should they override the previous ones or append? , when we fire new subscription request, should we close the previous?, UI indicator for open connection? etc...)

Anyway for people who want to use GraphiQL with subscriptions today, I wrote a blog post about it - https://dev-blog.apollodata.com/how-to-use-subscriptions-in-graphiql-1d6ab8dbd74b
and I will keep improving and iterating on that.

**Comment by asiandrummer** [comment]
cc @robzhu for context

**Comment by AGS-** [comment]
Hey @Urigo, this seems to have been sitting here for a while and since we haven't really been able to come to a consensus on this, and I'm not sure what direction we're taking with this, I'm going to close this for now. Thanks for the contribution.

**Pull request closed without merging**
