### PR TITLE
Upgrade codemirror-graphql to gls interface/parser 2.0x

### PR DESCRIPTION
**Pull request by acao**
- Update tests to support `__typename` in object type hint suggestions :shrug:
- Quite a breaking change! This should bump codemirror-graphql to 0.9.0

### CODE REVIEW

**Comment by acao** [comment]
This will probably break the netlify deployment of graphiql above (white screen), mostly just because codemirror-graphql is still at 0.8.3, graphiql still depends on that version, and will locally resolve it and try to use regenerator-runtime (which will be missing) in the babel build

**Comment by acao** [comment]
fixed!

**Comment by acao** [comment]
@graphql/graphiql-maintainers do you think we should upgrade graphiql to this version of codemirror-graphql so we can manually regression test this upgrade easier? it'll require figuring out the regenerator runtime issue. 

@ganemone had the idea to use `node: true` at the root in preset-env, but we will still need to add the regenerator runtime for the browsers list in graphiql (would like to be evergreen, but I promise @IvanGoncharov  we would match graphql-js's browserslist for graphiql). 

Where do we draw the line, since almost all of these libraries are browser facing? @Neitsch  see why there was so much going on in that PR? haha

**Comment by IvanGoncharov** [comment]
@acao Just to clarify: I meant you shouldn't support browsers that are not supported by `graphql-js`. But it's up to you guys to decide if you want to drop some additional browsers.

**Comment by acao** [comment]
@IvanGoncharov oh that's lovely news 💯 !!!

**Pull request merged**
