### PR TITLE
[Dependencies] add support for React >=0.14.8

### PR DESCRIPTION
**Pull request by zaneclaes**
Hey @leebyron, @spikebrehm and I were able to get GraphiQL successfully running on React 14.8 at Airbnb, but NPM install complains because it it has a peer dependency for React 15. Can you confirm that GraphiQL works properly with React 14?

### CODE REVIEW

**Comment by facebook-github-bot-1** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by facebook-github-bot-0** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by leebyron** [comment]
This seems good to me but cc'ing @asiandrummer to investigate the build failures.

**Comment by asiandrummer** [comment]
Hi @zaneclaes - I've just fixed the build failures by upgrading `react` to `v0.15.3` and including a mocked `Range` implementation. Could you please rebase to master?
The branch conflicts are caused by me and is probably complaining that I've changes the peer dependency versions from `0.15.1` to `0.15.3`. Apologies for that

**Comment by asiandrummer** [comment]
Thanks again!

**Comment by zaneclaes** [comment]
Thanks for the quick turnaround, @asiandrummer and @leebyron!

**Comment by zaneclaes** [comment]
@asiandrummer looks like you released `0.7.4` just before this got merged. Could you let me know when you can publish a new version?

**Comment by asiandrummer** [comment]
@zaneclaes - sure thing! I think I'll create another release very soon, supposedly by the end of this week.

**Comment by zaneclaes** [comment]
@asiandrummer any updates, here? We've been blocked for > 2 weeks.

**Comment by asiandrummer** [comment]
@zaneclaes I'm really sorry for the delay - just released [v0.7.5](https://github.com/graphql/graphiql/releases/tag/v0.7.5).

**Pull request merged**
