### PR TITLE
feat: typescript, tsx, jsx support for LSP server using babel

### PR DESCRIPTION
**Pull request by acao**
- introduces typescript, tsx and jsx support via babel parser plugins
- #1263 by @zth is an alternative to solving this problem which also supports reasonml, and potentially other  a non-ast branch by @zth using regular expressions should  be reconsidered.
-tests for typecript and tsx added
- `getQueryAndRange` changed to `parseDocument`, and made override-able as `parse` by `startServer`.

### CODE REVIEW

**Comment by divyenduz** [comment]
Does this do the same job as https://github.com/Quramy/ts-graphql-plugin? 
If yes, are there any usage docs that I can refer to? 🤔

**Comment by acao** [comment]
yes! the only difference now is that it will handle ts/tsx files when you open them. still need to get vscode workspaces configured correctly to read all the embedded graphql

**Comment by acao** [comment]
to add, the typescript language plugin is still valuable for a lot of cases.

**Comment by zth** [comment]
This looks good to me! This will allow people who want to support other languages than the mainstream ones (like ReasonML for me) to do that through replacing `parseDocuments`.  👍

**Comment by acao** [comment]
@zth last commit here fixes that bug i saw in discord, otherwise looks like everything is working fine! I've had some issues with setting up our example extension, but i think i understand what I'm missing after working with yours and @divyenduz 's more carefully.

**Pull request merged**
