### PR TITLE
add `StorageContext` and `HistoryContext` to `@graphiql/react`

### PR DESCRIPTION
**Pull request by thomasheyenbrock**
This PR continues to break up the huuuuge state of the `GraphiQL` component by adding two new contexts to `@graphiql/react`:
- The `StorageContext` exposes a `StorageAPI` instance. We assume that this context might be missing, i.e. a custom implementation using the components from `@graphiql/react` could choose to not store anything locally.
- The `HistoryContext` manages a `HistoryStore` instance and exposes methods to change its items as well as state for toggling the history sidebar.

### CODE REVIEW

**Comment by acao** [comment]
The latest changes of this PR are not available as canary, since there are no linked `changesets` for this PR.

**Comment by acao** [comment]
@harshithpabbati this coincides with your work on the new 2.0 storage API!

**Comment by acao** [comment]
@thomasheyenbrock it may not be the time to do it, but at some point we need to make StorageAPI instance allow async methods so people can use network or indexdb storage (localforage, idb, etc)

**Comment by thomasheyenbrock** [comment]
@acao thanks for making the link here! We can certainly follow up here, let's keep this PR scoped to refactoring the existing code and change functionality in a follow-up 🙂

**Comment by acao** [comment]
@thomasheyenbrock indeed, which is why I said "at some point", just keeping you aware of the plans!

here is some very similar prior art from our google summer of code intern as well:

https://github.com/graphql/graphiql/pull/1558/files

linked issue #1324

**Comment by acao** [comment]
The latest changes of this PR are not available as canary, since there are no linked `changesets` for this PR.

**Pull request merged**
