### PR TITLE
fix netlify build

### PR DESCRIPTION
**Pull request by acao**
add project reference for cm6 to graphql LS

### CODE REVIEW

**Review by thomasheyenbrock — APPROVED** [review]

**Comment by thomasheyenbrock** [comment]
Thank you for jumping in trying to fix this ❤️

**Comment by acao** [comment]
@thomasheyenbrock happy to help! did you see the google doc invite? I'll need someone's help for us to be able publish again

**Comment by acao** [comment]
@thomasheyenbrock would you be able to merge this one for me?

**Comment by thomasheyenbrock** [comment]
Sorry I only saw this now 😅 too late 🙈

**Pull request merged**
