### PR TITLE
chore: render query history panel only when it's toggled

### PR DESCRIPTION
**Pull request by harshithpabbati**
Rendering the history panel only when it's toggled instead of using CSS to hide it.

### CODE REVIEW

**Comment by acao** [comment]
ah! i think there's a bug in the new github actions workflow config where it doesn't work on PR create. if you push another commit it should test and deploy. I'll need to go fix that!

**Comment by acao** [comment]
hmm! still no dice! strange. but the PR looks great, thank you!

**Comment by acao** [comment]
this is a good move, thanks @harshithpabbati !

**Comment by harshithpabbati** [comment]
hmm, test cases failed because the history panel is no more available in dom.

**Comment by acao** [comment]
it should be once it's toggled open!

**Comment by harshithpabbati** [comment]
> it should be once it's toggled open!

yup, did that!

**Comment by acao** [comment]
thank you again @harshithpabbati !

**Comment by acao** [comment]
@harshithpabbati just need to fix the formatting bug, may have been introduced by changesets. thus why its easier when you run `yarn changeset` locally yourself!

**Comment by harshithpabbati** [comment]
@acao, fixed it!

**Pull request merged**
