### PR TITLE
fix: Hover docs were offset one position

### PR DESCRIPTION
**Pull request by mskelton**
Fixes https://github.com/graphql/graphiql/issues/2874

The hover docs were off by one position. This was due to autocomplete suggestions and hover docs using the same `getTokenAtPosition` function. For autocomplete, the behavior of the function was expected since your cursor is _after_ the token you want to get when requesting autocomplete results, but with hover docs you want the cursor _at_ the cursor position.

### CODE REVIEW

**Comment by acao** [comment]
@mskelton thanks for this! can you check that the hover positions for `codemirror-graphql` and `monaco-graphql` are still correct after this change? I know in `monaco-graphql` we re-use this method for certain, and the way that monaco and LSP server offsets work are slightly different, the former being base 1 and the latter base 0 if I recall offhand.  you could test with the `examples/monaco-graphql-webpack` example

**Comment by mskelton** [comment]
@acao I tried running the monoco-graphql-webpack example, but hovering didn't display any sort of information, so I'm not exactly sure how to validate it worked/didn't. I noticed the same behavior on main as well, so I'm a little confused.

**Comment by acao** [comment]
ohhh it's off by one _character_ not by one _line_. sorry it took me so long to look closely at this. ok, we don't need to worry as much about the other implementations

**Comment by acao** [comment]
@mskelton in case you're wondering, this will be released in an alpha first, before we return to stable state, because graphiql@3 is coming!

https://github.com/graphql/graphiql/pull/3219

**Pull request merged**
