### PR TITLE
History

### PR DESCRIPTION
**Pull request by tessalt**

### CODE REVIEW

**Comment by tessalt** [comment]
this was made by mistake I thought I was on my own fork :(

**Comment by asiandrummer** [comment]
@tessalt took a quick look and this seems to be an awesome contribution if it were to be one ;) are you planning to submit a real PR for this?

**Comment by tessalt** [comment]
@asiandrummer I was thinking about it but I've got some real UX issues to think through... basically i have no idea where to put the panel.

**Comment by asiandrummer** [comment]
@tessalt some idea I can throw:
* Expandable left-side window just like the doc explorer
* A toolbar button that opens a dialog that contains the query history

**Comment by tessalt** [comment]
@asiandrummer re-opened over here with some cleaned-up code https://github.com/graphql/graphiql/pull/232 (had a different history from this branch because of long story two computers)

**Pull request closed without merging**
