### PR TITLE
feat: set schema statically

### PR DESCRIPTION
**Pull request by acao**
this allows users to set the language service schema using an SDL string or an introspection JSON result

also in this PR:
- move and correct the `monaco.d.ts` (still no proper definitions, api intellisense)
- make `createData` simpler
- update docs, fix a typo
- add npmignore lines for tsbuild output which adds a whole MB or more to our npm package

CC @Nishchit14

### CODE REVIEW

**Comment by Nishchit14** [comment]
LGTM 🔥

**Comment by acao** [comment]
@Nishchit14 it is not sadly, been churning on the triple slash directives for monaco since last weekend :(. still can't get the monaco API patterns working right

**Comment by acao** [comment]
image

can't seem to get the module extensions working again

**Comment by Nishchit14** [comment]
I see I like the spec by reading the README. But as I am a newbie for TS and Monaco I could not go into the implementation. But I am learning it and I wish soon I can help you. :)

**Comment by acao** [comment]
this was accomplished in a better way in another upstream PR

**Comment by connorshea** [comment]
@acao sorry, could you explain what you mean by another upstream PR? I'm interested in this functionality and I'm not sure what you mean :)

**Comment by harshithpabbati** [comment]
@connorshea he means about this #1575 PR

**Pull request closed without merging**
