### PR TITLE
fix: unify how observables are consumed in different places

### PR DESCRIPTION
**Pull request by n1ru4l**
Closes https://github.com/graphql/graphiql/issues/1638

### CODE REVIEW

**Comment by acao** [comment]
thanks for this! most of the implementation out there are [like this](https://github.com/apollographql/GraphiQL-Subscriptions-Fetcher/blob/master/src/fetcher.ts), so can we introduce backwards compatibility somehow?

**Comment by n1ru4l** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/length

We could make an assumption based on the number of arguments, that however would fail if the observable implementation uses rest or default parameters.

Other than that I would not know any solution despite dealing with it in username in the fetcher function.

**Comment by n1ru4l** [comment]
This change would not break subscriptions-transport-ws (https://github.com/graphql/graphiql/issues/1638#issuecomment-673376897)

**Comment by n1ru4l** [comment]
Hey @acao, I guess you closed this due to lacking feedback from me. We already talked about AsyncIterables being the future for the fetcher prop but I think we should still address/tackle this issue. It is now back on my radar after having seen https://github.com/enisdenjo/graphql-ws/issues/93

So the conclusion was that all major observable implementation support both the

**A**
```tsx
type Observable {
  subscribe(next: function, complete: function, error: function):an any
}
```

and 

**B**
```tsx
type Observable {
  subscribe(args: {
    next: function;
    complete: function;
   error: function;
  }): any
}
```

signatures. I only see concerns for users that do not use any of those libraries that are ALSO mix and match both call signatures in their custom fetcher implementation. So IMHO it is pretty safe to simply unify the call signatures within GraphiQL to either use **A** and **B** in order to avoid workarounds like the following: https://github.com/enisdenjo/graphql-ws/issues/93#issuecomment-758625106

**Comment by acao** [comment]
it wont let me reopen this PR for some reason?

**Comment by acao** [comment]
oh because theres no 1.0.0 branch anymore that’s why

**Comment by n1ru4l** [comment]
I could send a new pr

**Pull request closed without merging**
