### PR TITLE
relint when schema changes

### PR DESCRIPTION
**Pull request by imolorhe**
Relint when schema changes. Codemirror 6 normally only runs linting whenever the document changes. However this means whenever the GraphQL schema changes, the linting is not run again until the document changes. This can be lead to confusing behaviors.

A new option was added to the linter [recently](https://github.com/codemirror/lint/commit/2da5dbdae05e28af5b6b52334f7b10e70fd1111e) that allows configuring a predicate to determine when the linter will be ran when the state changes. We are leveraging the same here to trigger linting whenever the schema or passed option changes.

Note: linting always runs on document changes irrespective of what we define in this predicate, _which is what we want_.

Related issue: https://github.com/altair-graphql/altair/issues/2242

### CODE REVIEW

**Comment by acao** [comment]
is it possible that we could update the example to show a simple schema change as well? perhaps just with a drop down?

**Review by acao — APPROVED** [review]

**Comment by imolorhe** [comment]
@acao I was trying to get the example package working but I was running into some issues with the duplicate @codemirror/state dependency instances which is why I haven't done that yet. We may have to move the example into the package itself like we did in codemirror-json-schema

**Comment by acao** [comment]
i got around that, issue. big pr coming, haha

**Comment by imolorhe** [comment]
Oh nice. Can't wait to see what you come up with!

**Comment by acao** [comment]
@imolorhe i was able to make this error go away by moving away from `basicSetup` package, whether it came from `codemirror` or `@codemirror/basic-setup`

**Pull request merged**
