### PR TITLE
chore: enable header editor by default

### PR DESCRIPTION
**Pull request by harshithpabbati**
This PR allows the latest version of the GraphiQL to persist and show the headers tab by default.

### CODE REVIEW

**Comment by dotansimha** [comment]
@acao I think this can get in? Seems like it's passing. 
I'm not sure about changing the behaviour of the flags, because this might be a breaking change? (it's super minor, but still a change in behaviour)

**Comment by acao** [comment]
I was not able to force push a rebase to this branch for some reason :(

**Comment by harshithpabbati** [comment]
oh I see, I will rebase it just a min!

**Comment by acao** [comment]
oh dang it was missing a changeset. I will add one for your commit!

**Pull request merged**
