### PR TITLE
The hint dom nodes lives outside the codemirror dom tree currently.

### PR DESCRIPTION
**Pull request by codeStryke**
Submitting another PR because I missed two cases in my earlier PR https://github.com/graphql/graphiql/pull/791.

### CODE REVIEW

**Comment by codeStryke** [comment]
@acao can you please review? Thanks!

**Comment by acao** [comment]
@codeStryke yeah for sure!

**Comment by orta** [comment]
Deploy preview looks good - thanks

**Comment by codeStryke** [comment]
Thanks!

**Pull request merged**
