### PR TITLE
chore: Full support i18n (i18next) excluding localization services

### PR DESCRIPTION
**Pull request by Xambey**
I implemented full localization support based on the i18next plugin. Two languages are currently supported:
- English
- Russian

P.S For verification, don't forget to clear localstorage

### CODE REVIEW

**Comment by Xambey** [comment]
image

**Comment by acao** [comment]
@Xambey this PR is awesome and super welcome! l18n was on our ad-hoc roadmap for GraphiQL 0.x.y and so this is a big chunk you just bit out of it!

Sorry for all the code changes in the last two weeks, looking at the diff briefly it looks like you got almost everything. If you need to do a `git pull origin master` its ok to have merge commits in the tree. One thing i see now is `babel-plugin-inline-json-import` is not found, so try re-running `yarn` with `--force` to ensure it resolves everything in all the package.json files in the workspace to a new write of the lockfile. And the latest upstream diff is probably just about appending `all` commas rather than `es5`.

Once you're ready to squash these commits, I'll make them into a `feat:` message that will kick out new minor versions of all the effected packages.

**Comment by acao** [comment]
@Xambey do you have time to finish this? If not, I can re-create the PR and pull in the upstream changes, and then if i @ you in the commit messages you'll get contribution credit, is that O.K?

**Comment by acao** [comment]
@IvanGoncharov  check this out! maybe you can help us with a Ukrainain translation as well when you get a chance?

**Comment by Xambey** [comment]
@acao I remember about this PR and i hope to have time to fix all conflicts today / tomorrow. If I don’t have time to do everything today/tomorrow, then I dont mind if you correct them. I have a lot of work right now (10-12 hours 6/7) and there is no time to solve all the problems on weekdays, this PR was also done as part of the work assignment

**Comment by acao** [comment]
@Xambey ok thanks! yeah if you can't get to it no big worries, i know what that's like. My job doesn't even sponsor my OSS work yet, haha! If in 48 hours you haven't been able to get to it I'll get it merged, because this is a huge win for us! Again, thanks for doing this!

**Comment by Xambey** [comment]
@acao everything seems to work, but there may be a problem with not working prompts when entering the editor. This was sometimes observed when building with a locally assembled codemirror-graphql package, please fix it, i don't understand why

**Comment by acao** [comment]
awesome, thank you I’ll check it out here in a few hours

**Comment by acao** [comment]
@Xambey when you refer to non-working prompts, which prompts are you referring to?

**Comment by acao** [comment]
thanks so much for all your work on this @Xambey! this is quite a huge diff it looks like, with a lot of unrelated changes, so I will turn this into a PR that's just the excellent translation/`react-i18n` work here soon, possibly after we officially drop React 15 support and can adopt hooks? just a few PRs down the line I was planning for that. would love to have your help on some of the other issues this PR addresses soon as well, however with such a widely used project, our changelog needs to be very punctuated and iterative. as @leebyron has instructed, and @IvanGoncharov would agree, and part of what has made the official graphql ecosystem so successful, is, ["One step at a time, ship often and prosper"](https://twitter.com/leeb/status/1167908050427990016)

**Pull request closed without merging**
