### PR TITLE
feat: enable custom storageNamespace to StorageAPI, improve StorageAPI

### PR DESCRIPTION
**Pull request by CaiYiLiang**
## Feat:

- Extend the flexibility to add custom storageNamespace, and discussion here #2794 @acao 

|Test-Screen|
|-|
|Screen Shot 2023-02-10 at 3 16 18 PM|

### CODE REVIEW

**Comment by acao** [comment]
@CaiYiLiang thanks for this!

re: the CLA bot - it wants you to sign the agreement with an email associated with your github account

**Review by thomasheyenbrock — COMMENTED** [review]
The list of props is already huge, and I have the fear of it growing larger and larger with each new feature we want to implement. I see an opportunity here for a different approach that doesn't involve a new prop.

We could create a new function in the `@graphiql/toolkit` package that return a wrapper around `localStorage` that optionally adds a prefix to the keys:

```ts
function createLocalStorage(prefix?: string): Storage
```

Users could then make use of the existing storage prop together with this new function:

```ts
import { createGraphiQLFetcher, createLocalStorage } from "@graphiql/toolkit"
import { GraphiQL } from "graphiql"

const fetcher = createGraphiQLFetcher({ url: "https://my.graphql.api" })
const storage = createLocalStorage("my-custom-prefix")

function CustomGraphiQL() {
  return <GraphiQL fetcher={fetcher} storage={storage} />
}
```

In my mind this is an improved separation of concerns and keeps the API of individual items more minimal and flexible. @CaiYiLiang what do you think?

**Comment by thomasheyenbrock** [comment]
By the way: It's awesome to see you jumping into action here and opening a PR for that existing issue, highly appreciated! 🙌 ❤️

**Comment by acao** [comment]
@thomasheyenbrock I totally forgot that this was one of the goals of `@graphiql/toolkit` when we created it! This is a great idea. We can add other options as we go.

This might be a bit more optimal, so it's easier to add options as we go, and not worry about ordered arguments:

```ts
const storage = createLocalStorage({ namespace: "my-custom-prefix" })
```

**Comment by CaiYiLiang** [comment]
> The list of props is already huge, and I have the fear of it growing larger and larger with each new feature we want to implement. I see an opportunity here for a different approach that doesn't involve a new prop.
> 
> We could create a new function in the `@graphiql/toolkit` package that return a wrapper around `localStorage` that optionally adds a prefix to the keys:
> 
> ```ts
> function createLocalStorage(prefix?: string): Storage
> ```
> 
> Users could then make use of the existing storage prop together with this new function:
> 
> ```ts
> import { createGraphiQLFetcher, createLocalStorage } from "@graphiql/toolkit"
> import { GraphiQL } from "graphiql"
> 
> const fetcher = createGraphiQLFetcher({ url: "https://my.graphql.api" })
> const storage = createLocalStorage("my-custom-prefix")
> 
> function CustomGraphiQL() {
>   return <GraphiQL fetcher={fetcher} storage={storage} />
> }
> ```
> 
> In my mind this is an improved separation of concerns and keeps the API of individual items more minimal and flexible. @CaiYiLiang what do you think?

Hello , for above suggestion. I have another proposed [PR-3022](https://github.com/graphql/graphiql/pull/3022)
Please check and let me know any concerns. Thank you

**Comment by CaiYiLiang** [comment]
> @CaiYiLiang thanks for this!
> 
> re: the CLA bot - it wants you to sign the agreement with an email associated with your github account

Hello, I have signed the contribution agreement. I am not quite sure why it still shows unauth status. While my another PR - https://github.com/graphql/graphiql/pull/3022 has no issue with CLA bot.

**Pull request closed without merging**
