### PR TITLE
Feat/add opt in for legacy decorators

### PR DESCRIPTION
**Pull request by acao**
Fix for #2294 thanks to @mvnhrd

hey there @mvnhrd thanks so much for your work on this!

I'm going to create a PR and rebase this branch now, and maybe make a few more commits, is that ok?

### CODE REVIEW

**Comment by acao** [comment]
you can get commit credit if you like, if you just sign the CLA using the same email the commits are signed with. if you'd rather not I can just give you a thank you in the git commit message!

**Comment by acao** [comment]
oh wait i see now you are also in CET so perhaps a bit too late to ask, haha!

**Comment by mvnrhd** [comment]
just signed it, but feel free to go ahead if it's too late now! 🙂

**Comment by acao** [comment]
@mvnrhd i finally reviewed it in more depth last night, this is a great first PR. For future reference, the change to `vscode-graphql` or `startServer` is not needed - the `MessageProcessor` accesses workspace config using `this._connection.workspace.getConfiguration()`  already!


This is a quite difficult case as it turns out looking more closely. Instantiating the parser properly based on config change events is proving to be tricky but I think I have a solution. for example, on MessageProcessor constructor() _or_ on the LSP server initialise event, we do not even have access to workspace settings yet!  This impacts vim users as well, and I'm finding bugs with how all the settings are loaded. I might have to do this PR myself on closer inspection, though I can re-use the logic from `findGraphQLTags`! 

It requires writing a a set of tests as well. I may create a separate PR that gives you attribution though! Please don't take it the wrong way, this PR helps me think about the problem, but the resulting PR will look quite different, is that ok?

**Comment by mvnrhd** [comment]
Hey @acao no worries! As said, I was not able to test my changes locally since I didn't find clear instructions how to actually run & debug the extension, the same applies for running tests. That's why I was already expecting that there will be further code changes needed. I'm just happy that we're tackling this now, so thanks a lot for your help. 😉

**Comment by acao** [comment]
@mvnrhd sorry we need to improve the docs for vscode - the vscode debugger tasks provide the language (LSP) and execution extension runners, of which you want the former. and the build tooling it uses changed because of graphiql so it doesn't always work right away. first a good `yarn build` across the repo and a `yarn compile` in `packages/vscode-graphql/` will ensure you can run the task for the language extension

**Comment by acao** [comment]
@mvnrhd it ended up being a really simple fix because of my misunderstanding - no settings needed, just `decorators-legacy`!

**Comment by acao** [comment]
@mvnrhd thank you for everything on this! The fix is released now. Sorry I made it so overcomplicated!

**Pull request closed without merging**
