### PR TITLE
chore: add jest-eslint-plugin, cleanup tests, docs and api site for LSP

### PR DESCRIPTION
**Pull request by acao**
- Add the jest-eslint-plugin for all packages that use jest
- re-add tests and coverage reporting for `codemirror-graphql`
- re-add docs to header
- fix lint-staged for md files

### CODE REVIEW

**Comment by acao** [comment]
@ryan-m-walker you wanna give this a fresh `yarn --force && yarn test`?

**Comment by ryan-m-walker** [comment]
@acao sure thing

**Comment by ryan-m-walker** [comment]
lint looks good to me now:

image

**Comment by acao** [comment]
@ryan-m-walker I think you're able to approve it even! even though you aren't a maintainer

**Comment by ryan-m-walker** [comment]
@acao cool i'm looking through the changes now

**Comment by acao** [comment]
@ryan-m-walker thank you!

**Pull request merged**
