### PR TITLE
Add the headers to the interface

### PR DESCRIPTION
**Pull request by antoinealej**
having the possibility to change the headers in the interface could be great.

I've added it, please let me know if I went in the right direction.

Thanks.

### CODE REVIEW

**Comment by andrewtpoe** [comment]
I am very interested in this feature, and hope to see it merged soon. Trying to build an api that requires auth headers with a tool that doesn't allow editing them has been challenging at best.

**Comment by wincent** [comment]
See previous incarnations of this proposal:

- PR #540
- Issue #500 
- Issue #565 
- Issue #148

**Comment by leebyron** [comment]
Thank you for your work on this, however unfortunately this is not something that belongs in the core GraphiQL project, but absolutely is something that should be supported as an add-on. I recommend you create this as a separate project and share it via npm.

GraphiQL is network agnostic, where the network implementation is provided as part of installation to best fit the use case. Not all networks even support headers, and even many of those that do would not want their users changing the header configuration.

GraphiQL supports a [customizable UI](https://github.com/graphql/graphiql#usage-examples) in the header and footer of the tool, and even includes a UI toolkit to help you build headers that look cohesive. Any installation of GraphiQL on an API which requires or desires header customization or other auth customization should rely on these customization features to provide them.

**Comment by yangli1990** [comment]
@leebyron thanks for the detailed explanation

> Not all networks even support headers, and even many of those that do would not want their users changing the header configuration

Out of curiosity which networks does GraphiQL support that doesnt support headers. Also, we can make the header section configurable? But honestly, not having a headers section doesn't stop a user from making a call with headers - it just makes it harder for all the people that need headers.

**Comment by leebyron** [comment]
> Out of curiosity which networks does GraphiQL support that doesnt support headers. 

At Facebook we've used MQTT, WebSockets, and others. Especially as subscriptions becomes more widely used, non-HTTP transports are becoming common.

Also, in my experience the most common desire to alter headers is for providing authentication tokens. That's great, but it probably deserves a UI designed for changing that authentication token rather than a generic header editor - something that would be different for every user of GraphiQL depending on how their particular auth works, which is why it's not built-in.

Instead, we sought to make it easy for people to add their own by making the header and footer of GraphiQL configurable and providing a UI toolkit you can use for easily making new elements like an auth-token addition that look cohesive.

We're not trying to intentionally make things difficult for people, instead we're trying to keep GraphiQL a focused and high quality tool for as many use cases as possible, while making it straight-forward to adjust for particular use cases. I still think that's the right direction for the project.

**Comment by jimscarver** [comment]
There seems to be enough interest in this to maintain a branch. Use of Graphql is growing fast and everyone needs graphql accessing their protected information resources. Is someone working on this? Who can help?

**Comment by asiandrummer** [comment]
@jimscarver I forget the links, but there are multiple branches/implementations that wrapped the custom header support around GraphiQL. I can only remember @OlegIlyenko's Sangria app having this capability.

**Comment by OlegIlyenko** [comment]
Indeed, meanwhile there are a lot of implementations that offer headers and many other features on top of the base GraphiQL functionality. just a few examples:

https://github.com/OlegIlyenko/graphiql-workspace
https://github.com/prismagraphql/graphql-playground
https://insomnia.rest/

**Pull request closed without merging**
