### PR TITLE
Improved grammar & punctuation in DEVELOPMENT.md

### PR DESCRIPTION
**Pull request by TallTed**

### CODE REVIEW

**Comment by acao** [comment]
Hey there @TallTed ! Thanks for opening this PR. I think you just need to run `yarn format`

**Comment by TallTed** [comment]
@acao -- I don't know how to _run `yarn format`_ (I work almost exclusively through the GitHub web UI), but I think I've resolved the conflicts (at least one was collision with another PR). Take another look?

**Comment by thomasheyenbrock** [comment]
@TallTed thanks! I just tried to run `yarn format` for you and push to your fork, but got a permission error. Did you allow updates by maintainers?

**Comment by TallTed** [comment]
@thomasheyenbrock -- Thanks. Yes, I always allow updates by maintainers. I _think_ the issue here is that my fork was accidentally branched from `B2o5T/graphiql` instead of `graphql/graphiql`. Easiest route to resolving everything appears to be to close this PR, drop my fork, start a new fork from `graphql/graphiql`, and re-apply my changes toward a new PR. I'll do that later today.

**Pull request closed without merging**
