### PR TITLE
feat: upgrade to graphql@15.0.0 for #1191

### PR DESCRIPTION
**Pull request by acao**
Have `graphql@15.0.0` working as a baseline, without necessarily adding support for new language features yet. Consequently, it requires an upgrade to `graphql-config-rc.2`. This is why we are still in alpha! Further PRs will follow that address things like interfaces implementing interfaces, etc

- [x] use `instrospectionQuery()` rather than constant (deprecated)
- [x] bump resolutions for 15
- [x] minor validation error formating issues
- [x] ensure GraphiQL works end to end (view deploy preview, cypress suite)
- [x] issue with `graphql-config` and server tests? potentially `graphql-config` is not working with 15.
- [x] check server for regressions, use with a vscode extension
- [x] manually check for more specific regressions in GraphiQL, other LSP implementations that are related to breaking changes.

### CODE REVIEW

**Comment by acao** [comment]
@urigo so we are using `graphql-config@2.2.1` still, and it seems theres a bug with the introspection result in this test:

https://github.com/graphql/graphiql/blob/chore/graphql-15-rc/packages/graphql-language-service-server/src/__tests__/GraphQLCache-test.js#L46

when i print out the result of the introspection request, i get:
`Error: Must provide Source. Received: undefined.`

**Comment by acao** [comment]
only bug left is that this type is deprecated in graphql 15:
image

@ardatan @urigo

maybe i can open an issue?

**Comment by acao** [comment]
https://github.com/ardatan/graphql-tools/pull/1 i think this is the right place?

**Comment by Urigo** [comment]
I think this was already fixed on `graphql-toolkit`'s master.

tomorrow we'll make sure to have updated versions of it published

**Comment by acao** [comment]
@Urigo everything looks good now, thank you!

**Comment by acao** [comment]
oh, tests were fine, but build not so much, spoke too soon there
we just updated to the latest `graphql-config`, maybe @ardatan knows whats up?

image

**Comment by acao** [comment]
@IvanGoncharov it's finally ready for you to review, what do you think?

**Comment by acao** [comment]
@IvanGoncharov I think the only thing we missed here as a baseline is removing the peer dependencies on lower versions of graphql. We should only support 14 and 15 now correct?

**Pull request merged**
