### PR TITLE
style: Don't convert single \n to <br>

### PR DESCRIPTION
**Pull request by leonardehrenfried**
As described in #3155 we (OpenTripPlanner) tend to have quite long, multi-paragraph descriptions of our fields.

In Markdown a single `\n` is ignored and only two `\n` should lead to a new paragraph being started.

markdown-it makes this fairly easy to achieve, which is why this PR is tiny.

### Before

Screenshot from 2023-08-28 12-59-50

### After

Screenshot from 2023-08-28 13-00-02

I've also taken the liberty to update the dev instructions.

Many thanks for this wonderful tool!

### CODE REVIEW

**Comment by acao** [comment]
@leonardehrenfried thank you for this, this is exactly how it should behave, I agree. I recall there was disagreement some years back and again with the redesign about this, I will look up some issues/discussions/? when I have more time. @thomasheyenbrock or @jonathanawesome what do you think?

one last thing, can you add a changeset? then it'll be ready to go!

**Comment by acao** [comment]
awesome, thanks @leonardehrenfried ! I think we would make this a minor release for @graphiql/react as well

**Comment by leonardehrenfried** [comment]
Changeset was updated.

**Comment by leonardehrenfried** [comment]
Could I perhaps have another review for this?

**Comment by acao** [comment]
hey thanks for this! i'll come back to this later today or tomorrow and release it with some other new features for this `@graphiql/react` minor release

**Comment by leonardehrenfried** [comment]
Lovely thanks!

**Comment by leonardehrenfried** [comment]
Could I perhaps have another review for this, please?

**Comment by leonardehrenfried** [comment]
@acao Isn't this good to merge?

**Comment by acao** [comment]
sorry I hope to have more time for this in the coming months. my current commitments are for my day job and for a grant to work on the GraphQL LSP server that I'm wrapping up

**Comment by acao** [comment]
i think the only thing still stumping me is whether this constitutes a breaking change for some use cases, and whether there is some kind of markdown it config that solves the issue this intended to solve? maybe it was a workaround for the previous markdown library, was it marked? I need to look at the original history from, say, tag 0.7.y era or earlier to determine what the original purpose was

**Comment by dimaMachina** [comment]
I agree with @acao that this should not affect the current stable version of GraphiQL, let's fix it in GraphiQL v4

**Pull request merged**
