### PR TITLE
Add netlify action to github-workflows

### PR DESCRIPTION
**Pull request by daemon1024**
Ref: #1501

### CODE REVIEW

**Comment by acao** [comment]
awesome work! there's no need for `yarn build-bundles` or possibly even `yarn build` if I understand how typedoc works correctly? either way, `yarn build-ts && yarn build-demo` is probably all we need for a clean build, as `yarn build` also builds codemirror which is needed for demos/bundles, but not for typedoc

**Comment by daemon1024** [comment]
> there's no need for `yarn build-bundles` or possibly even `yarn build` 

I just based it on the current `netlify.toml`
> `yarn build-ts && yarn build-demo` is probably all we need for a clean build

Got it. Will change it. 

Also should I remove the `netlify.toml` is it needed anymore?

**Comment by acao** [comment]
@daemon1024 the netlify.toml should remain the same for now, as it's used for the deploy preview and master build. after this PR is when we would revisit the `netlify.toml` deploy preview steps and see what we can improve there.

this action will fail on merge because the environment secrets, however I can just add those myself, do I have commit rights on this branch?

**Comment by daemon1024** [comment]
> after this PR is when we would revisit the `netlify.toml` deploy preview steps and see what we can improve there.

:+1: 
> this action will fail on merge because the environment secrets, however I can just add those myself

You can set secrets for your repository by going to [`Setting -> Secrets`](https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets) .

> do I have commit rights on this branch? 

I guess not, i can provide you with the access if needed?

**Comment by acao** [comment]
yes please, and then I can complete this PR and we will be on our way!

**Comment by acao** [comment]
oh you don't need to invite me to the whole repo, just check the box in this PR in the bottom right to allow maintainers access

**Comment by daemon1024** [comment]
> oh you don't need to invite me to the whole repo, just check the box in this PR in the bottom right to allow maintainers access

you already have that access then :)

**Comment by daemon1024** [comment]
Something more is needed with `yarn build-ts` ? I see the workflow check failing , after I added that!

**Comment by acao** [comment]
oh and we have to change the `on` condition too, oops. now its gonna deploy to the root subdomain on each commit, haha yikes

**Comment by daemon1024** [comment]
only deploy on master branch? 

      on:
          pull_request:
            branches:
              - master

**Comment by acao** [comment]
yes. theres an issue and I'll have to come back to this later. thanks for all your help!

**Comment by daemon1024** [comment]
> yes. 

will add it then.
>theres an issue and I'll have to come back to this later. 

No problem
>thanks for all your help!

Happy to help. Let me know if I can help with something else.

**Comment by daemon1024** [comment]
> there's no need for `yarn build-bundles` or possibly even `yarn build` if I understand how typedoc works correctly? either way, `yarn build-ts && yarn build-demo` is probably all we need for a clean build, as `yarn build` also builds codemirror which is needed for demos/bundles, but not for typedoc

i guess the run command should be ` yarn build-ts && yarn build-docs `

**Pull request closed without merging**
