### PR TITLE
docs: typo - `/* GraphQL */` not `/* GraphiQL */`!

### PR DESCRIPTION
**Pull request by acao**
huge typo. caused this user bug https://github.com/graphql/graphiql/issues/2843#issuecomment-1294685543

### CODE REVIEW

**Comment by ADTC** [comment]
@acao I should have mentioned that I had actually tried the different spelling and it still didn't work:

image

But this version works:

image

So does it have to be positioned after the equals (`=`) sign? This is a `.jsx` file btw.

**Comment by acao** [comment]
@ADTC very good question - thanks for asking! both should work. looks like the regex for the syntax highlighting for case #1 is broken, then! Are you able to see validation/autocompletion even withought highlighting in case #1?

**Comment by ADTC** [comment]
@acao I'm sorry, but I'm only using the syntax highlighting extension right now. Hope you can check that on your end. Thank you!

**Comment by ADTC** [comment]
Hope you managed to check. But it's okay. I kinda like the second version TBH. It doesn't take up one extra line.

**Pull request merged**
