### PR TITLE
docs: Add maintainers section, including new maintainers

### PR DESCRIPTION
**Pull request by acao**
hey there @yoshiakis and @imolorhe, here it is as promised finally!

- [@imolorhe](https://github.com/imolorhe)
- [@yoshiakis](https://github.com/yoshiakis)

both colleauges have contributed great value to all three and now one of these repos for years. they have also helped triage issues and addressed user concerns in objective ways that demonstrate very good maintainer habits

@benjie do you want to be listed as active or not?

@brianwarner will let us know what we should do next. should i just make this into its own MAINTAINERS.md file?

### CODE REVIEW

**Comment by imolorhe** [comment]
@acao at the moment I am not going to be fully active, as I have a couple of other things ongoing, more like passive active 🙂 just managing expectations.

**Comment by acao** [comment]
that’s fine! whenever you’re able. help with PR reviews is one of the biggest things I need help with

**Comment by yoshiakis** [comment]
@acao Thank you 😄

**Comment by acao** [comment]
ok, I will remove you @benjie no problem, the door is always open but you have plenty on your plate I'm sure. 

@imolorhe to clarify, you don't mind being added to the list? we'll be glad to have your help in any capacity 💯 but if you'd like to wait, that's fine, too!

**Comment by imolorhe** [comment]
@acao That's fine. I'll help out as much as I can.

**Pull request merged**
