### PR TITLE
Remove political statements from open source projects.

### PR DESCRIPTION
**Pull request by eranshapira**
Code should be technical, without any political statements. if we go down that route, we harm the open source community.

### CODE REVIEW

**Review by sharonamr — APPROVED** [review]

**Review by enjikaka — APPROVED** [review]

**Review by ezerk — APPROVED** [review]
in such times, where politicians (world wide) are lacking the ability to solve issues properly (and even make things worse), we as humans and open source community should not follow those lame paradigms that only divide people and increase tension. 

@acao despite my personal affection to graffiti, i believe that arranging palestinian-israeli hackathon (or other coding event that will also have a human aspect) would have a greater and positive effect. i would happily to take part in such event.

life matters, and we all have mutual responsibility for it
let's think of ways to increase collaboration

**Review by hagai-reuveni — APPROVED** [review]

**Review by ziso — APPROVED** [review]

**Review by aviadhahami — APPROVED** [review]

**Review by ChenSade — APPROVED** [review]

**Review by adylevy — APPROVED** [review]
+1

**Review by yardenshoham — APPROVED** [review]

**Review by code613 — APPROVED** [review]

**Comment by Evilu** [comment]
> @acao despite my personal affection to graffiti, i believe that arranging palestinian-israeli hackathon (or other coding event that will also have a human aspect) would have a greater and positive effect. i would happily to take part in such event.

Actually that's an awesome Idea, I would love to participate.

**Review by marat-asadurian — APPROVED** [review]

**Review by orenk86 — APPROVED** [review]

**Review by SnirShechter — APPROVED** [review]

**Review by ofirule — APPROVED** [review]

**Review by moriatuch — APPROVED** [review]

**Review by moriatuch — APPROVED** [review]

**Review by michfa — APPROVED** [review]

**Review by naorz — APPROVED** [review]

**Comment by leebyron** [comment]
The GraphQL technical steering committee is working on a policy to guide the use of political speech from the voice of a GraphQL project. The original author chose to revert the original change via #1879 until we complete that policy. This should resolve this issue, so I am closing it.

As a reminder, all discussion within GraphQL projects must adhere to our [Code of Conduct](https://github.com/graphql/foundation/blob/main/CODE-OF-CONDUCT.md).

**Pull request closed without merging**
