### PR TITLE
[plugin-code-exporter/plugin-explorer]: exclude peer dependencies and dependencies from bundle

### PR DESCRIPTION
**Pull request by B2o5T**
## `@graphiql/plugin-explorer`
| before                                                                                  | after |
|:---------------------------------------------------------------------------------------------------:|:--------------:|
| image |   image        |

## `@graphiql/plugin-code-exporter`

| before                                                                                  | after |
|:---------------------------------------------------------------------------------------------------:|:--------------:|
| image |     image      |

### CODE REVIEW

**Comment by acao** [comment]
@B2o5T one issue here is - how do users use this plugin if they are using the CDN version of react?

**Comment by B2o5T** [comment]
@acao how this was changed with the previous implementation?

**Comment by acao** [comment]
@B2o5T there are a few examples where users were able to use the bundled CDN build of this plugin with the CDN graphiql. Each plugin should provide an unbundled module version and a bundled cdn version, as with GraphiQL, @graphiql/toolkit and @graphiql/react. We don't have to solve this problem now, but it will lead to a regression until we fix it

**Comment by B2o5T** [comment]
@acao Since a new major is coming, we can go back to this problem in case of reporting it

**Comment by thomasheyenbrock** [comment]
@B2o5T Too late with my review, sorry 🙇  @acao has a good point, and I don't think the new major will solve this. Removing the bundling of dependencies breaks the CDN examples, in particular this one: https://github.com/graphql/graphiql/blob/main/packages/graphiql-plugin-explorer/examples/index.html

At least the UMD build has to bundle up all dependencies, with the exception of the ones where we define globals: https://github.com/graphql/graphiql/blob/main/packages/graphiql-plugin-explorer/vite.config.ts#L23-L28

**Comment by B2o5T** [comment]
@thomasheyenbrock ok! I'll fix it

**Pull request merged**
