### PR TITLE
feat: [RFC] GraphiQL rewrite for monaco editor, react context and redesign, i18n

### PR DESCRIPTION
**Pull request by acao**
(here, we've re-created #1468 against a non-forked branch, so RFCs are visible in pull requests here) (see: #1446 for details)

image

go ahead and give this rewrite PR a whirl! this is what the new GraphiQL 2.0.0 beta will be based on.

***Note***: use right click context menu/`f1` command palette for the full experience!

## Context for State Management

- makes use of `useReducers` 
- `SchemaProvider`, `SchemaContext`
- `SessionProvider`, `SessionContext`
- `EditorProvider`, `EditorContext`

thank you so much to @cshaver , @zephraph , @ryan-m-walker, @ncthbrt , and @sgrove for contributing to or chiming in on this effort! no small effort by any means.

## Monaco Editor

we spiked on and integrated the fantastic monaco-editor with this PR, using our now monaco-graphql mode.

## Redesigned Components and Theme UI

thanks to @walaura 's original work, and @cshaver and @harshithpabbati for moving it forward. we are well underway with implementing the redesign!

## Temporary Breakages

some features are temporarily disabled by this effort, in the interest of rapid iteration:

- persisted operations (though your previous query history works in the left sidebar, soon to be deprecated)
- variables hint/lint aka code completion/diagnostics for variables json. coming soon!

## Preview

(use right click/f1 context menu for funsies!)

https://deploy-preview-1523--graphiql-test.netlify.app/bundle/dist/

### CODE REVIEW

**Comment by acao** [comment]
rebasing this one after the monaco mode merge! this PR should reduce in size quite substantially

**Comment by harshithpabbati** [comment]
Looks like my i18n PR is failing. I will try to fix it

**Comment by acao** [comment]
@harshithpabbati no worries! working on it as well, it seems to be this:

> File '/home/rikki/projects/graphiql/packages/graphiql/src/locales/en/Errors.json' is not listed within the file list of project '/home/rikki/projects/graphiql/packages/graphiql/tsconfig.json'. Projects must list all files or use an 'include' pattern.

funky that it worked before and not now, haha

**Comment by harshithpabbati** [comment]
Oh, it's weird

**Comment by acao** [comment]
@harshithpabbati you can re-create it locally by running `yarn build-demo`. you might need to `yarn && yarn build` one time beforehand to reset your codebase

**Comment by acao** [comment]
@harshithpabbati the funny thing is that this bug is *only* with storybook, however all of these are builds that pass:

- graphiql min/dev webpack
- monaco vanilla webpack example
- graphiql example webpack

**Comment by acao** [comment]
@harshithpabbati i think i've found the resolution! turns out you were very close with `includes`

**Comment by acao** [comment]
1.0.0 has been released, now for the 2.0.0 rewrite to be merged to master!

**Pull request merged**
