### PR TITLE
fix: Set headers to localstorage

### PR DESCRIPTION
**Pull request by harshithpabbati**
This PR is to add headers to local storage.

### CODE REVIEW

**Comment by acao** [comment]
looks good! let's make this an opt-in option via props though, perhaps?

**Comment by harshithpabbati** [comment]
Sure @acao, I will update it

**Comment by acao** [comment]
thank you!

the reason I wanted to do this is so that the security risk could be opt-in.

**Comment by acao** [comment]
lets make it `shouldPersistHeaders` maybe?

**Comment by harshithpabbati** [comment]
done @acao 👍

**Comment by acao** [comment]
awesome, thanks @harshithpabbati !

**Pull request merged**
