### PR TITLE
fix: Set headers to localstorage

### PR DESCRIPTION
**Pull request by harshithpabbati**
This PR is to add headers to local storage.

@acao can you review this PR?

### CODE REVIEW

**Comment by acao** [comment]
@harshithpabbati yes thanks for this but *please* don't ask for me to review in every single PR comment anymore. we've talked about this before, haha. of course I will review it its my job

**Comment by acao** [comment]
@harshithpabbati no worries, just being grumpy haha!

you'll want to change this PR to be against master now, and pull in the latest upstream changes

**Comment by acao** [comment]
oh wait, this no longer applies. make it against 1.0.0 branch my bad

headers tab is not in core graphiql for 2.0.0

**Comment by harshithpabbati** [comment]
> oh wait, this no longer applies. make it against 1.0.0 branch my bad
> 
> headers tab is not in core graphiql for 2.0.0

Sure, I will change this towards 1.0.0 branch

**Pull request closed without merging**
