### PR TITLE
Upgrade codemirror-graphql to 0.8.3

### LINKED ISSUE #773: Please upgrade codemirror-graphql to 0.8.3 (in order to support graphql 14.0.0)
The graphiql package now supports graphql 14.0.0 as peer dependecy which is great! 👍 (See  #739).

However, when I install graphiql with yarn, it installs codemirror-graphql  0.7.1 which does not support graphql 14.0.0 as peer dependency. So in order to fully support graphql 14.0.0 transitively I guess graphiql must upgrade codemirror-graphql to 0.8.3 [here](https://github.com/graphql/graphiql/blob/master/package.json#L54). (Because codemirror-graphql 0.8.3 supports graphql 14.0.0 as peer dependency.)

### PR DESCRIPTION
**Pull request by jonaskello**
Fixes #773

### CODE REVIEW

**Comment by AGS-** [comment]
Merged! Thanks for taking the time to fix this!

**Comment by mikefowler** [comment]
Yes! Thanks @AGS-! Are you able to get a new version published, as well?

**Comment by felixfbecker** [comment]
@AGS could we get a release for this? Would love to get rid of the log spam

**Comment by hiei23** [comment]
@AGS- Can you publish a new version?

**Comment by stephahart** [comment]
@AGS- Also looking for a new version 😄

**Comment by austinnichols101** [comment]
Note that there are still sub-dependencies of `codemirror-graphql` that do not support graphql 14.  
https://github.com/graphql/codemirror-graphql/issues/258

IMO, we need a new release #793 after the sub-dependencies have been updated.

**Comment by acao** [comment]
resolved by https://github.com/graphql/graphql-language-service/pull/353

need to cut a new release

**Comment by acao** [comment]
@austinnichols101 see https://github.com/graphql/codemirror-graphql/issues/258

**Pull request merged**
