### PR TITLE
fix: limit all codemirror css rules to .graphiql-container

### PR DESCRIPTION
**Pull request by Yahkob**
Reopened PR of https://github.com/graphql/graphiql/pull/3032 after CLA issues

### CODE REVIEW

**Comment by Yahkob** [comment]
Ok think that fixed, @thomasheyenbrock. Sorry for the noise opening duplicate PRs.

**Comment by thomasheyenbrock** [comment]
Changes look good! 🙌 No idea why Netlify is acting up, will try to have a look over the weekend

**Comment by acao** [comment]
@Yahkob deploy preview is working now! i forgot to ask, can you add a changeset as per the bot comment? a patch should be fine

**Review by B2o5T — APPROVED** [review]
Thanks!

**Pull request merged**
