### PR TITLE
Delete index.js.flow

### PR DESCRIPTION
**Pull request by B2o5T**
saw with a new prettier setup https://github.com/graphql/graphiql/pull/3259 prettier wanted to prettify these files, I guess they are no longer used?

### CODE REVIEW

**Comment by acao** [comment]
they are around for backwards compatibility for users. @benjie what do you think we should do with these?

**Comment by acao** [comment]
@B2o5T the scripts can be removed in a separate PR like you had before, but the legacy flow-typed files are a different question. Can we do seperate PRs again please?

**Comment by B2o5T** [comment]
@acao Yeah, I didn't see that the base PR is this one! will remove them in improvement prettier PR

**Comment by acao** [comment]
@benjie @dwwoelfel are you or your users still using `flow-typed` with the language services? A cursory search of code on github showed only projects 4+ years old were still using `flow-typed` with our libraries

**Comment by benjie** [comment]
I believe that Facebook is the main place where Flow and GraphiQL were used together. Maybe @mjmahone will have some clue as to whether this is still needed or not. Personally I'm in favour of removing it - no types is better than out of date types, and maintenance of them is a burden.

**Review by acao — APPROVED** [review]

**Pull request merged**
